Update minimal flow stack
opennms-forge/stack-play pull request #20
Opened 2023-01-26 12:33 UTC by indigo423

Use the latest stable release tag as the default floating tag instead bleeding. The ElasticSearch version is updated from 7.6.2 to 7.17.5 including the drift plugin. The Helm plugin is updated from 8.0.0 to 8.0.4. To make it easier for the user, I've created a provisioning file for Grafana to populate the data sources in Grafana accordingly. The default admin password is changed from `mypass` to `admin` to make it consistent with the Horizon default login in the Web UI.

2023-01-27 09:59 UTC, christianpape requested changes

2023-01-27 09:59 UTC, christianpape commented on minimal-flows/docker-compose.yaml
>        - "4729:4729/udp"
Maybe use the multi protocol listener udp/9999 here. It will allow to send IPFIX, NetFlow v5/v9 and SFlow records.

2023-01-27 14:26 UTC, agalue commented
Maybe the following helps as a reference:
https://github.com/agalue/onms-flows-overview

That deployed a complete end-to-end test with flows using Minions and Sentinels and descrives how to use `pmacctd` to send flows for testing purposes.

2023-02-02 10:19 UTC, indigo423 commented
> Maybe the following helps as a reference: https://github.com/agalue/onms-flows-overview
> 
> That deploys a complete end-to-end test with flows using Minions and Sentinels, and it describes how to use `pmacctd` to send flows for testing purposes.

I think this is exactly the missing piece to build a full-stack example. Thanks for pointing this out.

2023-02-09 12:13 UTC, merged